### PR TITLE
Update to Linux 5.14 drivers

### PR DESCRIPTION
**Pull request by dumbbell**
This is the backport of the DRM drivers from Linux 5.14.

~~This branch is based on the `update-to-v5.13` branch and therefore depends on the merge of #224.~~ This branch is now based on `master` because #224 was merged.

**Progress**:

### Changes in Linux 5.14

You can read this Phoronix article to learn about the changes in the DRM drivers in Linux 5.14:
https://www.phoronix.com/news/Linux-5.14-DRM-Drivers

In particular, the i915 driver starts to support GPUs in Intel 12th gen CPU (Alder Lake). However, this support is very early stage and will likely not work! It was disabled by default in Linux 5.14.

### Patches to linuxkpi

This update depends on the following patches to linuxkpi in FreeBSD:
* ~~https://reviews.freebsd.org/D38145~~
* ~~https://reviews.freebsd.org/D38146~~
* ~~https://reviews.freebsd.org/D38147~~
* ~~https://reviews.freebsd.org/D38148~~
* ~~https://reviews.freebsd.org/D38149~~
* ~~https://reviews.freebsd.org/D38150~~
* ~~https://reviews.freebsd.org/D38151~~
* ~~https://reviews.freebsd.org/D38152~~
* ~~https://reviews.freebsd.org/D38153~~
* ~~https://reviews.freebsd.org/D38154~~
* ~~https://reviews.freebsd.org/D38155~~
* ~~https://reviews.freebsd.org/D38156~~
* ~~https://reviews.freebsd.org/D38157~~
* ~~https://reviews.freebsd.org/D38158~~
* ~~https://reviews.freebsd.org/D38159~~
* ~~https://reviews.freebsd.org/D38160~~
* ~~https://reviews.freebsd.org/D38161~~
* ~~https://reviews.freebsd.org/D38162~~
* ~~https://reviews.freebsd.org/D38163~~

All patches are merged into `main`.

### How to test

You need to run a recent FreeBSD 14-CURRENT to test it.

Here are some instructions:

1. You need to checkout the [FreeBSD `main` src branch](https://github.com/freebsd/freebsd-src), and compile a kernel from that branch:

    ```sh
    git clone https://github.com/freebsd/freebsd-src.git
    cd freebsd-src
    make -j8 buildkernel DEBUG_FLAGS=-g

    # This installs the kernel under another name, `kernel.drm`. Thus, you keep the default kernel
    # in case of trouble.
    sudo make installkernel DEBUG_FLAGS=-g INSTKERNNAME=kernel.drm
    ```
2. You need to checkout the branch referenced in this pull request and compile it:

    ```
    git clone -b update-to-v5.14 https://github.com/dumbbell/drm-kmod.git
    cd drm-kmod
    make -j8 DEBUG_FLAGS=-g
    sudo make install DEBUG_FLAGS=-g KMODDIR=/boot/kernel.drm
    ```

    This will need access to the FreeBSD src tree cloned above. I don't remember the name of the variable to point the build to it. You can link `/usr/src` to your clone and it will be enough.

3. You will need GPU firmwares in the `kernel.drm` directory as well. To compile and install them:

    ```
    git clone -b drm-5.14 https://github.com/dumbbell/drm-kmod-firmware.git
    cd drm-kmod-firmware
    make -j8 DEBUG_FLAGS=-g OSVERSION=1400000
    sudo make install DEBUG_FLAGS=-g KMODDIR=/boot/kernel.drm OSVERSION=1400000
    ```

4. Load the relevant driver(s) as you usually do.

### CODE REVIEW

**Comment by mekanix** [comment]
On my Vega based laptop loading the driver causes the display brightness to go to zero (or very low value) so everything is very dark. I will bisect to find out more.

**Comment by mekanix** [comment]
After update build fails and I had to revert cebfbfe2674712445e9bbe980da582f67e420bc0. If it's just something missing in freebsd-src, I can just wait for an update, otherwise please advise.

**Comment by dumbbell** [comment]
Did you used the `linuxkpi-5.14` branch in freebsd-src (i.e. not the `linuxkpi-5.13` branch used for the Linux 5.13 DRM drivers update)?

**Comment by mekanix** [comment]
I did, I just double checked. Just for reference, drm-kmod is at 97fd6e9ad8415489880294ed5ff29bf421137af6 while freebsd-src is at https://github.com/dumbbell/freebsd-src/commit/7b564598d2d79f5ceee40f5eb865b3d80cabb3c6

**Comment by dumbbell** [comment]
Sorry, I forgot to push two commits. This is done (force-pushed).

**Comment by mekanix** [comment]
OK, builds now. Let me bisect the brightness bug and I'll get back to you with my findings.

**Comment by mekanix** [comment]
So, the brightness is not a bug, it's a feature. The offending commit is this:
```
git show 5a4fc2bb075c88b3f4900b73f3b43210b7af2d63
commit 5a4fc2bb075c88b3f4900b73f3b43210b7af2d63
Author: Alex Deucher <alexander.deucher@amd.com>
Date:   Thu Dec 10 02:30:39 2020 -0500

    drm/amdgpu/display: restore the backlight on modeset (v2)

    To stay consistent with the user's setting.

    v2: rebase on multi-eDP support

    Bug: https://gitlab.freedesktop.org/drm/amd/-/issues/1337
    Reviewed-by: Harry Wentland <harry.wentland@amd.com>
    Signed-off-by: Alex Deucher <alexander.deucher@amd.com>

diff --git a/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c b/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
index a7d786e3fa..e9865b6b8a 100644
--- a/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
+++ b/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
@@ -9086,6 +9086,12 @@ static void amdgpu_dm_atomic_commit_tail(struct drm_atomic_state *state)
        /* Update audio instances for each connector. */
        amdgpu_dm_commit_audio(dev, state);

+#if defined(CONFIG_BACKLIGHT_CLASS_DEVICE) ||          \
+       defined(CONFIG_BACKLIGHT_CLASS_DEVICE_MODULE)
+       /* restore the backlight level */
+       if (dm->backlight_dev)
+               amdgpu_dm_backlight_set_level(dm, dm->brightness[0]);
+#endif
        /*
         * send vblank event on all events not handled in flip and
         * mark consumed event for drm_atomic_helper_commit_hw_done
```
The question remains how do I make it brighter, because keys on my laptop do not produce any difference. Are there commands I can use for brightness control for Xorg and tty?

**Comment by dumbbell** [comment]
I will need to check how this works.

Meanwhile you can remove the `BACKLIGHT_CLASS_DEVICE` line in `kconfig.mk` at the root of drm-kmod and recompile.

**Comment by mekanix** [comment]
If I do remove it I get the following error:
```
make DEBUG_FLAGS=-g
===> dmabuf (all)
Warning: Object directory not changed from original /usr/home/meka/repos/drm/drm-kmod/dmabuf
===> linuxkpi (all)
Warning: Object directory not changed from original /usr/home/meka/repos/drm/drm-kmod/linuxkpi
===> ttm (all)
Warning: Object directory not changed from original /usr/home/meka/repos/drm/drm-kmod/ttm
===> drm (all)
Warning: Object directory not changed from original /usr/home/meka/repos/drm/drm-kmod/drm
===> amd (all)
===> amd/amdgpu (all)
Warning: Object directory not changed from original /usr/home/meka/repos/drm/drm-kmod/amd/amdgpu
/usr/local/bin/ccache cc  -O2 -pipe '-DKBUILD_MODNAME="amdgpu"' '-DLINUXKPI_PARAM_PREFIX=amdgpu_' -DDRM_SYSCTL_PARAM_PREFIX=_amdgpu -DLINUXKPI_VERSION=50000 -DCONFIG_DRM_AMDGPU_CIK -DCONFIG_DRM_AMDGPU_SI -DCONFIG_DRM_AMD_DC -DCONFIG_DRM_AMD_DC_SI -DCONFIG_AMD_PMC -DCONFIG_DRM_I915_FORCE_PROBE='"*"' -DCONFIG_DRM_I915_REQUEST_TIMEOUT=20000 -DCONFIG_DRM_I915_CAPTURE_ERROR -DCONFIG_DRM_I915_USERFAULT_AUTOSUSPEND=250 -DCONFIG_DRM_I915_STOP_TIMEOUT=100 -DCONFIG_DRM_I915_PREEMPT_TIMEOUT=640 -DCONFIG_DRM_I915_HEARTBEAT_INTERVAL=2500 -DCONFIG_DRM_I915_TIMESLICE_DURATION=1 -DCONFIG_DRM_I915_MAX_REQUEST_BUSYWAIT=8000 -DCONFIG_DRM_I915_FENCE_TIMEOUT=10000 -DCONFIG_DRM_MIPI_DSI -DCONFIG_DRM_PANEL_ORIENTATION_QUIRKS -DCONFIG_DRM_FBDEV_EMULATION -DCONFIG_DRM_FBDEV_OVERALLOC=100 -DCONFIG_ARCH_HAVE_NMI_SAFE_CMPXCHG -DCONFIG_DEBUG_FS -DCONFIG_DMI -DCONFIG_FB -DCONFIG_MTRR -DCONFIG_PCI -DCONFIG_PM -DCONFIG_SMP -DCONFIG_ACPI -DCONFIG_ACPI_SLEEP -DCONFIG_X86 -DCONFIG_X86_PAT -DCONFIG_64BIT -DCONFIG_AS_MOVNTDQA -DCONFIG_COMPAT -DCONFIG_X86_64 -DCONFIG_DRM_AMD_DC_DCN -DCONFIG_DRM_AMD_DC_DCN3_0 -DCONFIG_DRM_AMD_DC_DCN3_01 -DCONFIG_DRM_AMD_DC_DCN3_02 -DCONFIG_DRM_AMD_DC_DCN3_1  -fno-strict-aliasing -Werror -D_KERNEL -DKLD_MODULE -nostdinc  -I/usr/home/meka/repos/drm/drm-kmod/linuxkpi/gplv2/include -I/usr/home/meka/repos/drm/drm-kmod/linuxkpi/bsd/include -I/usr/src/sys/compat/linuxkpi/common/include -I/usr/home/meka/repos/drm/drm-kmod/linuxkpi/dummy/include -I/usr/home/meka/repos/drm/drm-kmod/include -I/usr/home/meka/repos/drm/drm-kmod/include/drm -I/usr/home/meka/repos/drm/drm-kmod/include/uapi -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/acp/include -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/amdgpu -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/amdkfd -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/amdgpu_dm -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/dc -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/dc/clk_mgr/ -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/dc/inc -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/dc/inc/hw -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/dmub/inc -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/include -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/display/modules/inc -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/include -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/include/asic_reg -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/inc -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/powerplay -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/powerplay/hwmgr -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/powerplay/smumgr -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/swsmu -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/swsmu/smu11 -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/swsmu/smu12 -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/pm/swsmu/smu13 -I/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/scheduler -include /usr/home/meka/repos/drm/drm-kmod/amd/amdgpu/opt_global.h -I. -I/usr/src/sys -I/usr/src/sys/contrib/ck/include -fno-common -g -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fdebug-prefix-map=./machine=/usr/src/sys/amd64/include -fdebug-prefix-map=./x86=/usr/src/sys/x86/include -fdebug-prefix-map=./i386=/usr/src/sys/i386/include     -MD  -MF.depend.atombios_encoders.o -MTatombios_encoders.o -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -msoft-float  -fno-asynchronous-unwind-tables -ffreestanding -fwrapv -fstack-protector -Wall -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef -Wno-pointer-sign -D__printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error=tautological-compare -Wno-error=empty-body -Wno-error=parentheses-equality -Wno-error=unused-function -Wno-error=pointer-sign -Wno-error=shift-negative-value -Wno-address-of-packed-member -Wno-format-zero-length -Wno-expansion-to-defined -Wno-pointer-arith -Wno-format -Wno-cast-qual -Wno-pointer-sign -Wno-unused-but-set-variable -Wno-unused-but-set-variable  -mno-aes -mno-avx  -std=iso9899:1999 -c /usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c -o atombios_encoders.o
/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c:258:6: error: conflicting types for 'amdgpu_atombios_encoder_init_backlight'
void amdgpu_atombios_encoder_init_backlight(struct amdgpu_encoder *encoder)
     ^
/usr/home/meka/repos/drm/drm-kmod/drivers/gpu/drm/amd/amdgpu/atombios_encoders.h:37:6: note: previous declaration is here
void amdgpu_atombios_encoder_init_backlight(struct amdgpu_encoder *amdgpu_encoder,
     ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/home/meka/repos/drm/drm-kmod/amd/amdgpu
*** Error code 1

Stop.
make[1]: stopped in /usr/home/meka/repos/drm/drm-kmod/amd
*** Error code 1

Stop.
make: stopped in /usr/home/meka/repos/drm/drm-kmod
```

**Comment by dumbbell** [comment]
Indeed the code is wrong. Try this patch:
```diff
diff --git a/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c b/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c
index ac79fb4cc2..4176d2440d 100644
--- a/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c
+++ b/drivers/gpu/drm/amd/amdgpu/atombios_encoders.c
@@ -255,7 +255,8 @@ amdgpu_atombios_encoder_fini_backlight(struct amdgpu_encoder *amdgpu_encoder)
 
 #else /* !CONFIG_BACKLIGHT_CLASS_DEVICE */
 
-void amdgpu_atombios_encoder_init_backlight(struct amdgpu_encoder *encoder)
+void amdgpu_atombios_encoder_init_backlight(struct amdgpu_encoder *encoder,
+    struct drm_connector *drm_connector)
 {
 }
 
```

**Comment by evadot** [comment]
> So, the brightness is not a bug, it's a feature. The offending commit is this:
> 
> ```
> git show 5a4fc2bb075c88b3f4900b73f3b43210b7af2d63
> commit 5a4fc2bb075c88b3f4900b73f3b43210b7af2d63
> Author: Alex Deucher <alexander.deucher@amd.com>
> Date:   Thu Dec 10 02:30:39 2020 -0500
> 
>     drm/amdgpu/display: restore the backlight on modeset (v2)
> 
>     To stay consistent with the user's setting.
> 
>     v2: rebase on multi-eDP support
> 
>     Bug: https://gitlab.freedesktop.org/drm/amd/-/issues/1337
>     Reviewed-by: Harry Wentland <harry.wentland@amd.com>
>     Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
> 
> diff --git a/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c b/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
> index a7d786e3fa..e9865b6b8a 100644
> --- a/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
> +++ b/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c
> @@ -9086,6 +9086,12 @@ static void amdgpu_dm_atomic_commit_tail(struct drm_atomic_state *state)
>         /* Update audio instances for each connector. */
>         amdgpu_dm_commit_audio(dev, state);
> 
> +#if defined(CONFIG_BACKLIGHT_CLASS_DEVICE) ||          \
> +       defined(CONFIG_BACKLIGHT_CLASS_DEVICE_MODULE)
> +       /* restore the backlight level */
> +       if (dm->backlight_dev)
> +               amdgpu_dm_backlight_set_level(dm, dm->brightness[0]);
> +#endif
>         /*
>          * send vblank event on all events not handled in flip and
>          * mark consumed event for drm_atomic_helper_commit_hw_done
> ```
> 
> The question remains how do I make it brighter, because keys on my laptop do not produce any difference. Are there commands I can use for brightness control for Xorg and tty?

Does it works with backlight(8) ?

**Comment by mekanix** [comment]
`backlight(8)` works almost perfectly, except it reports 100% when it boots when it's really 0%. I didn't know it even exists, to thank you @evadot!

@dumbbell I tried your patch but it leads to more changes. I can try to alter the code as compiler tells me and sent the patch or you think it's not worth it and better path would be initializing `backlight` calls? Or something else?

I had a [little inquiry on how 7900XT works with Linux](https://lists.freedesktop.org/archives/amd-gfx/2023-January/088810.html) and TL;DR: it probably uses CHIP_IP_DISCOVERY and AMD official driver is not open source one.

**Comment by dumbbell** [comment]
> @dumbbell I tried your patch but it leads to more changes. I can try to alter the code as compiler tells me and sent the patch or you think it's not worth it and better path would be initializing `backlight` calls? Or something else?

If backlight(8) works (which I discovered too, thanks :), then don't bother fixing the !`CONFIG_BACKLIGHT_CLASS_DEVICE` code. It will be more useful to understand where/how to restore the correct brightness.

**Comment by gizahNL** [comment]
Perhaps it's silly (I have zero kernel development experience), but wouldn't it be a good idea to try & focus on targeting one of the linux LTS branches, and then starting to use the Linux backports stuff to automatically generate backport code that interfaces with that stable linux kernel API?

**Comment by dumbbell** [comment]
@gizahNL: Do you mean working on DRM from Linux 5.10, then 5.15, then whatever is the next LTS release?

Let's imagine we don't lag behind versions, I think this wouldn't work for DRM drivers specifically because new hardware support is added on a regular basis. But this argument is somewhat moot given the fact we are working on Linux 5.14 at the same time Linux 6.2 is in the middle of its release cycle.

The second argument which makes this impracticle is the way we backport the code. We chose to backport code from Linux to this drm-kmod repository one Git commit at a time, working our way from e.g. `v5.13` to `v5.14`, instead of copying files. The main reason is the ability to bisect commits like @mekanix did to isolate a specific change which causes a regression. We can then analyze the regression to understand if it's specific to FreeBSD (i.e our linuxkpi lacks something or it must be adapted to this new Linux code) or it's global (in which case we see if a fix exists in a future version of Linux). If we want to continue this approach, we would need to go through the entire Git history anyway.

Another benefit of this one-commit-at-a-time workflow is that we can adapt linuxkpi slowly, instead of having a huge amount of unrelated compile errors.

**Comment by gizahNL** [comment]
> @gizahNL: Do you mean working on DRM from Linux 5.10, then 5.15, then whatever is the next LTS release?
> 
> Let's imagine we don't lag behind versions, I think this wouldn't work for DRM drivers specifically because new hardware support is added on a regular basis. But this argument is somewhat moot given the fact we are working on Linux 5.14 at the same time Linux 6.2 is in the middle of its release cycle.
> 
> The second argument which makes this impracticle is the way we backport the code. We chose to backport code from Linux to this drm-kmod repository one Git commit at a time, working our way from e.g. `v5.13` to `v5.14`, instead of copying files. The main reason is the ability to bisect commits like @mekanix did to isolate a specific change which causes a regression. We can then analyze the regression to understand if it's specific to FreeBSD (i.e our linuxkpi lacks something or it must be adapted to this new Linux code) or it's global (in which case we see if a fix exists in a future version of Linux). If we want to continue this approach, we would need to go through the entire Git history anyway.
> 
> Another benefit of this one-commit-at-a-time workflow is that we can adapt linuxkpi slowly, instead of having a huge amount of unrelated compile errors.

I meant: to have linuxkpi focus on a "stable" linux version; While using linux-backports scripts to generate compat code that targets that linux version. That way linuxkpi would settle once complete enough, and driver porting can continue without linuxkpi changes being required (hopefully)

**Comment by dumbbell** [comment]
The code for linuxkpi doesn't come from Linux itself. The DRM drivers are licensed under an MIT license, that's why we can copy them. That's not the case for the rest of the kernel which is GPLv2.

Another problem is that the Linux kernel doesn't try to maintain compatibility for drivers between versions. They are very strict with the public KBI so that a userland program compiled for an old Linux kernel will work with a new one. However, they have no intention to do the same for kernel code. Therefore if we have a linuxkpi based on Linux 5.15, DRM drivers from Linux 5.14 may not compile against it.

Also, we update linuxkpi whenever we find something missing/has changed while working on the DRM drivers (or other developers on e.g. the iwlwifi driver). We don't work explicitly on linuxkpi to provide a complete interface (this would be a huuuge work).

We also take shortcuts, like we add stub functions to linuxkpi which return 0/false/a dumb result, just to make drivers compile, for features we can't work on right now. For instance, several power management-related functions. Or memory-management functions which we will need when we want to add support for compute on AMD Radeon.

**Comment by gizahNL** [comment]
Thank you for the excellent explanation!

**Comment by grahamperrin** [comment]
> Thank you for the excellent explanation!

I thought the same. Something like it could **very** usefully form part of a future [status report](https://www.freebsd.org/status/) and/or an article in FreeBSD Journal.

**Comment by dumbbell** [comment]
I'm not sure there is anything to troubleshoot for Intel 12th gen CPU at this point. The code is clearly beta in 5.14. I'm afraid we would simply spend time debugging something which is unfinished. That time would be better invested in working on 5.15+.

**Comment by christian-moerz** [comment]
Got it. On a second run, it ended in a frozen system with blank screen. Was in the middle of trying to coax it into doing a dump, but I guess I'll save myself the headache for the moment.

I'll take you up on the teams call option in the next few days so I can hopefully contribute further.

**Comment by dumbbell** [comment]
All patches to freebsd-src are now committed to `main`.

**Comment by orbitz** [comment]
👍🏽

**Pull request merged**
