### PR TITLE
Bring back AGP support, fix it, and clean it up

### PR DESCRIPTION
**Pull request by TijlCoosemans**
This series of patches restores AGP support on i386. The reverts are all clean and unmodified.  The other commits fix a few issues, restore upstream Linux code, and put FreeBSD code behind #ifdef so it should be easier to merge Linux code.

### CODE REVIEW

**Comment by linz2h** [comment]
Please upgrade your GPU, don't bring the complexity into the code base

**Comment by wulf7** [comment]
What a complexity? The code should remain in tree if it has users and maintainers.

I think the main reason it was removed is GPL-ed header. Unfortunately this issue still persists.
But given the fact that the header does not contain any code or comments, it looks like we can just replace license line to make it BSD-compatible.

**Comment by evadot** [comment]
> 

The GPLv2 header is indeed one of the reasons.
The other are we are in 2022 and PCI-e is almost 20 years old now and that there have been talk to remove agp from main.

**Comment by evadot** [comment]
> The GPL header is a drm header, not a linuxkpi header.

Doesn't matter, I've almost replaced all GPL code so I can bring back drm into base so it should be rewritten.

> I believe the code was removed because FreeBSD modifications were all over the place and this caused problems when merging from upstream. 

Nope, as said before it's because we're in 2022.

> This patch series should alleviate that because the diff with upstream is a lot smaller now and every difference is behind #ifdef FreeBSD. Linux still supports AGP, FreeBSD still supports AGP, the drm drivers still support AGP, so I don't see why we shouldn't support it. 

Because Linux supports it isn't a reason.
AGP code is now legacy in upstream Linux, see https://github.com/torvalds/linux/commit/04dfe19a5ed683e91d8285df5be1dbde2f2f39af
It's part of 5.14, sure we're not at it yet but I don't want to bring back all the CONFIG_DRM_LEGACY stuff in base.

> If FreeBSD main removes agp(4) then it will still be part of stable branches for several years.

**Pull request merged**
