### PR TITLE
drm-kmod 5.6 import

### PR DESCRIPTION
**Pull request by neelchauhan**
As my 5.7-wip branch was rejected, I have made a 5.6-wip branch to continue.

This is not based on my previous 5.7-wip branch. Some of the 5.7-wip commits were (sort of) rebased and integrated into 5.6-wip.

# Requires

Recent 14.0-CURRENT ~~along with~~:

 * ~~https://reviews.freebsd.org/D31131~~
 * ~~https://reviews.freebsd.org/D30706~~

**Update:** These patches have been committed.

# Tested on

 * i915: Intel WhiskeyLake (HP Spectre x360 13-ap0053dx)
 * amdgpu: Via @unrelentingtech

### CODE REVIEW

**Comment by evadot** [comment]
Please rebase the fix commits that you did (bisect to find the original commit and squash).

**Comment by neelchauhan** [comment]
I have done (at least some of) the squashing of the commits.

The `drm_print.h` is something I'm not 100% sure on if it's done correctly, but then there were big changes between 5.5 and 5.6.

**Comment by unrelentingtech** [comment]
Probably would make sense to also drop my `Revert "drm/amdgpu: invalidate mmhub semaphore workaround in gmc9/gmc10"` together with the `drm/amdgpu: invalidate mmhub semaphore workaround in gmc9/gmc10` it reverts as well. i.e. make it look like you never applied that already-applied commit :)

**Comment by neelchauhan** [comment]
> Probably would make sense to also drop my `Revert "drm/amdgpu: invalidate mmhub semaphore workaround in gmc9/gmc10"` together with the `drm/amdgpu: invalidate mmhub semaphore workaround in gmc9/gmc10` it reverts as well. i.e. make it look like you never applied that already-applied commit :)

Sadly, I was unable to do this:

    root@fatbox:~/drm-kmod # git rebase -i master
    Auto-merging drivers/gpu/drm/amd/amdgpu/gmc_v9_0.c
    CONFLICT (content): Merge conflict in drivers/gpu/drm/amd/amdgpu/gmc_v9_0.c
    error: could not apply 3378d29f9... drm/amdgpu: avoid using invalidate semaphore for picasso
    Resolve all conflicts manually, mark them as resolved with
    "git add/rm <conflicted_files>", then run "git rebase --continue".
    You can instead skip this commit: run "git rebase --skip".
    To abort and get back to the state before "git rebase", run "git rebase --abort".
    Could not apply 3378d29f9... drm/amdgpu: avoid using invalidate semaphore for picasso
    root@fatbox:~/drm-kmod #

**Comment by evadot** [comment]
> Please rebase the fix commits that you did (bisect to find the original commit and squash).

Your last commit (https://github.com/freebsd/drm-kmod/pull/94/commits/fb2b9575e8d8f87565d04b45cabb9e8584fc8715) is exactly what I'm talking about above.

**Comment by neelchauhan** [comment]
My last commit was a result of me in progress of squashing and splitting commits. I plan to squash it.

**Comment by neelchauhan** [comment]
I should have fixed the mismerges by now. Please review/comment/merge/etc..

**Comment by wulf7** [comment]
I just created 5.6-wip branch to do further work on 5.6 import.
Could you move all Makefile additions (both i915 and amdgpu) in to commits which actually added the files and redo MR on top of the new branch?

**Comment by neelchauhan** [comment]
> Could you move all Makefile additions (both i915 and amdgpu) in to commits which actually added the files and redo MR on top of the new branch?

I have a new PR based on the current 5.6-wip branch: #97.

In 5.5, I have added the i915 files to the Makefile in searate commits from where they were added: https://github.com/freebsd/drm-kmod/commit/71a0b7f86f51950d4af48a575e337c38dfec1620

I would prefer not to mix these two commits together, but can if it's desired/required.

**Pull request closed without merging**
