### PR TITLE
drm-kmod 5.6 import (Revision 2)

### PR DESCRIPTION
**Pull request by neelchauhan**
This continues the work from #94, rebased on the current 5.6-wip branch.

### CODE REVIEW

**Comment by wulf7** [comment]
Could you move every line added in commits https://github.com/freebsd/drm-kmod/pull/97/commits/495bd975432a00417d0ef2befd1ed2e1b077ff22 and https://github.com/freebsd/drm-kmod/pull/97/commits/df57dbde7a4569cd3910ff807b04e39b7b2a6fd2 to commit which introduced respective files?

**Comment by neelchauhan** [comment]
Sure, I can do that.

**Comment by neelchauhan** [comment]
I have attempted to work on it, and it seems in df57dbd, flags were added to existing files, so I think it would cause more problems than it's worth.

We add the files to the Makefile in a separate commit in 5.5-wip: https://github.com/freebsd/drm-kmod/commit/71a0b7f86f51950d4af48a575e337c38dfec1620

Also, I'm worried this would make merging harder in the future.

**Comment by wulf7** [comment]
The main goal is not to make perfect commit history, but to make it bissectable. So you can just skip file if you don't know which commit it belongs to.

**Comment by neelchauhan** [comment]
I have split up/squashed the Makefile entries into the commits when new files are introduced.

**Pull request merged**
