### PR TITLE
Make drm_timestamp_precision and drm_vblank_offdelay visible outside …

### PR DESCRIPTION
**Pull request by jorgem-seq**
…the compilation unit

Signed-off-by: Jorge Maidana <jorgem.seq@gmail.com>

### CODE REVIEW

**Comment by evadot** [comment]
I don't like modifying upstream code, what is your motiviation for that ?

**Comment by jorgem-seq** [comment]
They are used in drivers/gpu/drm/drm_sysctl_freebsd.c, it was my mistake, they should have the #ifdef __linux__ ...

**Comment by jorgem-seq** [comment]
I was thinking that the drm_* files were FreeBSD only, that's why I obviate the explanation.

**Comment by jorgem-seq** [comment]
This is better: https://github.com/jorgem-seq/drm-kmod/commit/b725fb652a2cf967b0bc34f957d4caa4c29ea747
You can close this PR, thanks for your time.

**Comment by jorgem-seq** [comment]
I'm closing this pull request and opening another for the updated tree
and to explain the fix.

**Pull request closed without merging**
