### PR TITLE
linuxkpi: Use acpi from base linuxkpi

### PR DESCRIPTION
**Pull request by wulf7**
Depends on https://reviews.freebsd.org/D26603

### CODE REVIEW

**Comment by evadot** [comment]
Everything should be in master now, can you change the target branch.
Also we need some FreeBSD_version check for now as we leave a month for users to update.

**Comment by wulf7** [comment]
> Everything should be in master now
5.4-cleanup-lkpi is not merged in to master yet.

**Comment by evadot** [comment]
> > Everything should be in master now
> 
> 5.4-cleanup-lkpi is not merged in to master yet.

Meh, I though I did merge the acpi patches, I'll do that this week.

**Comment by evadot** [comment]
Hi,

Just merge the acpi cleanup patches to both master and 5.4-lts.
Could you rebase this MR on master ?
If no changes are needed for this to be applied on 5.4-lts I'll just cherry-pick the commit after merging.
Thanks.

**Comment by wulf7** [comment]
pull request to master branch created.

**Pull request closed without merging**
