### PR TITLE
Import 5.7-wip branch

### PR DESCRIPTION
**Pull request by neelchauhan**
This branch compiles without any extra `linuxkpi` patches in base, and is not based on my earlier `5.7-wip` branch.

I cannot guarantee this works, as I haven't tested this, and I have sold my `amdgpu` system.

### CODE REVIEW

**Comment by neelchauhan** [comment]
Thanks for your suggestions, @unrelentingtech. Now I'll just have to test this on Intel (I no longer have my `amdgpu` laptop).

**Comment by wulf7** [comment]
@neelchauhan: I just branched 5.7-wip. Could you apply this pull request to it?

**Comment by neelchauhan** [comment]
Done. Sorry for the delay.

**Comment by wulf7** [comment]
Pulled in. Thanks!

**Pull request merged**
