### PR TITLE
WIP: Implement `dma_buf_poll`

### PR DESCRIPTION
**Pull request by qiu-x**
Hello,
This is my attempt at implementing `dma_buf_poll`. I'm not very familiar with DRM, so I don't know what else is needed for this feature to work correctly or how to test it (feedback would be appreciated).

From my testing it looks like software that uses `dma_buf_poll` like Waypipe is working correctly. 

But the problem is that I do not know how to replace `poll_wait` function from the Linux implementation, since `fo_poll` on FreeBSD does not have a `poll_table` parameter.

### CODE REVIEW

**Comment by unrelentingtech** [comment]
Where exactly do you see waypipe intentionally polling a dmabuf? The only way we hit it so far is with the **inherited file descriptor test**. Waypipe does not use *it*, Waypipe just uses `poll()` on arbitrary descriptors it does not know anything about.

It's hard to find anything that uses this, looks like our best hope is the igt-gpu-tools test suite which uses this in:

- [prime_busy test](https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/59c59f45b8433300b1b45cc9abc4b86dd0f81084/tests/prime_busy.c) — probably what we're looking for
- [gem_busy benchmark](https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/59c59f45b8433300b1b45cc9abc4b86dd0f81084/benchmarks/gem_busy.c#L271)
- [amd_prime test](https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/59c59f45b8433300b1b45cc9abc4b86dd0f81084/tests/amdgpu/amd_prime.c#L379) (not in an interesting way, just an assert)
- [vc4_dmabuf_poll](https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/blob/59c59f45b8433300b1b45cc9abc4b86dd0f81084/tests/vc4_dmabuf_poll.c) (we don't have vc4)

@evadot ping, you said you've been porting igt…

**Comment by wulf7** [comment]
The main problem is that you try to import 5.16 upstream code in to our 5.7 based branch. You should base your code on 5.7 branch or update our dma-buf code to 5.16 state if it is still compatible on KPI level

> But the problem is that I do not know how to replace `poll_wait` function from the Linux implementation, since `fo_poll` on FreeBSD does not have a `poll_table` parameter.

`poll_wait` is not required on native FreeBSD code. `selrecord()` should be called from poll handler if it decided to wait for some events. Obviously, this change is dysfunctional as long as poll handler is not calling `selrecord()` in some way.

**Comment by jbeich** [comment]
> It seems hard to find anything that uses this

[gamescope](https://www.freshports.org/x11-wm/gamescope) triggers `dma_buf_poll` e.g.,
```
$ dtrace -n ':::dma_buf_poll:entry { ustack() }' -c 'gamescope glxgears' | c++filt
[...]
              libc.so.7`_poll+0xa
              gamescope`imageWaitThreadMain()+0x1e0
              gamescope`decltype ((static_cast<void (*std::__1::__invoke<void (*)()>(void (*&&)()))()>({parm#1}))())+0x12
              gamescope`void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()>&, std::__1::__tuple_indices<>)+0x25
              gamescope`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)()> >(void*)+0x6d
              libthr.so.3`0x82c1b7aa8
```
https://github.com/Plagman/gamescope/blob/3.11.14/src/steamcompmgr.cpp#L471
https://github.com/Plagman/gamescope/blob/3.11.14/src/steamcompmgr.cpp#L4132

`return (ENOTSUP)` doesn't seems sufficient given the following glitches:
gamescope glxgears before
gamescope gtk3-demo before

**Comment by wulf7** [comment]
NetBSD has poll implementation: https://github.com/NetBSD/src/blob/trunk/sys/external/bsd/drm2/linux/linux_dma_resv.c#L1269

**Comment by wulf7** [comment]
I tried to port this code little more: https://github.com/wulf7/drm-kmod/commit/56f326d34c1e69e88a21a8395d189e0abb80046b
Not sure if it works at all as I do not know what it does.

**Comment by evadot** [comment]
@wulf7 We have poll implemented here : https://github.com/evadot/drm-subtree/blob/master/drmkpi/drmkpi_dma_buf.c

I plan to use this as a base to have in-base linuxkpi dma buf support in the near futur.

**Comment by thisplacestinksoffascism** [comment]
> @wulf7 We have poll implemented here : https://github.com/evadot/drm-subtree/blob/master/drmkpi/drmkpi_dma_buf.c
> 
> I plan to use this as a base to have in-base linuxkpi dma buf support in the near futur.

I think the following is the updated link to that code:
https://github.com/evadot/drm-subtree/blob/master/drmkpi/drmcompat_dma_buf.c

**Pull request closed without merging**
